/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillList: typeof import('./src/components/bill/BillList.vue')['default']
    EditPass: typeof import('./src/components/user/EditPass.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Home: typeof import('./src/components/home/Home.vue')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    MyLogin: typeof import('./src/components/user/MyLogin.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupplierList: typeof import('./src/components/supplier/SupplierList.vue')['default']
    Tips: typeof import('./src/components/home/Tips.vue')['default']
    UserAdd: typeof import('./src/components/user/UserAdd.vue')['default']
    UserDetail: typeof import('./src/components/user/UserDetail.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
    UserUpdate: typeof import('./src/components/user/UserUpdate.vue')['default']
  }
}
